package com.example.los.events.application;

import java.math.BigDecimal;

/**
 * A loan application was submitted for assessment.
 *
 * <p>Carries only the risk-relevant figures the downstream workflow needs.
 * {@code applicantReference} is a pseudonym generated by the application
 * service: it is not a name, an email address, a phone number or a national
 * identifier, and it cannot be resolved to a person outside that service.
 *
 * @param applicationId      opaque application identifier
 * @param applicantReference pseudonymous applicant identifier
 * @param amountMinorUnits   requested principal in minor currency units, avoiding floating point
 * @param currency           ISO 4217 currency code
 * @param termMonths         requested repayment term in months
 * @param purpose            loan purpose category
 * @param declaredAnnualIncomeMinorUnits declared gross annual income in minor units
 * @param productCode        internal product identifier
 */
public record ApplicationSubmittedV1(
        String applicationId,
        String applicantReference,
        long amountMinorUnits,
        String currency,
        int termMonths,
        String purpose,
        long declaredAnnualIncomeMinorUnits,
        String productCode)
        implements ApplicationEventPayload {

    public static final int SCHEMA_VERSION = 1;

    /** Convenience view of the principal for readability in tests and reports. */
    public BigDecimal amountMajorUnits() {
        return BigDecimal.valueOf(amountMinorUnits).movePointLeft(2);
    }
}
